### ISSUE TITLE
Upgrade tests with known source edits

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/providertest#64]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We should be able to test upgrades across some incompatible SDK changes which require program changes, e.g. https://github.com/pulumi/pulumi-gcp/pull/1305/files - serviceAccount was renamed serviceaccount.

**Comment by t0yv0** [comment]
@danielrbradley perhaps you have a quick example how it's already possible on the new API? Much appreciated.

**Comment by danielrbradley** [comment]
Hmm, need to think about that. It's probably quite easy to add if it's not there.
